language: python

python: 
  - "3.8"

services:
  - docker

before_script: pip install docker-compose

script: 
  - docker-compose build user-api-app
  - docker exec -it user-api bash
  - alembic upgrade head
  - docker-compose run --rm user-api-test