"""add foreign key constraint

Revision ID: 14b144db69cb
Revises: b0ec5f5529c7
Create Date: 2021-07-05 16:37:34.424253

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '14b144db69cb'
down_revision = 'b0ec5f5529c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key('FK_ADDRESS_USERS', 'users', 'address', ['address_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('FK_ADDRESS_USERS', 'users', type_='foreignkey')
    op.drop_column('users', 'address_id')
    # ### end Alembic commands ###
