"""add unique constraint to zip code and building number from address table

Revision ID: 8f9f0c2187d2
Revises: e35cec4cde52
Create Date: 2021-07-11 12:17:29.563258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f9f0c2187d2'
down_revision = 'e35cec4cde52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_address_values', 'address', ['zip_code', 'building_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_address_values', 'address', type_='unique')
    # ### end Alembic commands ###
