"""add new column to user as foreign key table

Revision ID: a428b26847fa
Revises: 10a768b05d2b
Create Date: 2021-07-04 17:49:19.447749

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a428b26847fa'
down_revision = '10a768b05d2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, 'users', 'address', ['address_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'address_id')
    # ### end Alembic commands ###
