"""rename the constraint

Revision ID: cafa1483c4f2
Revises: a428b26847fa
Create Date: 2021-07-05 15:47:07.004303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cafa1483c4f2'
down_revision = 'a428b26847fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('FK_ADDRESS_USER', 'users', 'address', ['id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('FK_ADDRESS_USER', 'users', type_='foreignkey')
    # ### end Alembic commands ###
