"""add unique constraint to first name last name email from  user table

Revision ID: e35cec4cde52
Revises: 0b5b3bdbd4a6
Create Date: 2021-07-11 12:16:41.066156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e35cec4cde52'
down_revision = '0b5b3bdbd4a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_values', 'users', ['first_name', 'last_name', 'email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_values', 'users', type_='unique')
    # ### end Alembic commands ###
